# Generated by Django 3.0.2 on 2020-02-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("pen_name", models.CharField(max_length=300)),
                ("year_birth", models.IntegerField()),
                ("year_death", models.IntegerField(null=True)),
                ("country", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="authors/")),
                ("biography", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.IntegerField()),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(max_length=1000)),
                ("cover", models.ImageField(upload_to="books_covers/")),
                ("authors", models.ManyToManyField(to="lib_app.Author")),
                ("genres", models.ManyToManyField(to="lib_app.Genre")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="lib_app.Publisher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="genres",
            field=models.ManyToManyField(to="lib_app.Genre"),
        ),
    ]
