# Generated by Django 3.0.2 on 2020-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
